# Generated by Django 5.2.3 on 2025-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_image',
            field=models.ImageField(blank=True, null=True, upload_to='reference_images/'),
        ),
    ]
