# Generated by Django 5.2.3 on 2025-07-12 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_reference_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_file',
        ),
    ]
