# Generated by Django 5.2.3 on 2025-07-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
