# Generated by Django 5.2.3 on 2025-07-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_reference_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reference_image',
        ),
    ]
