# Generated by Django 5.2.3 on 2025-07-12 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_reference_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_unit', models.FloatField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.supplier')),
            ],
        ),
    ]
